### ISSUE TITLE
gradle subproject failing to find test result files

### ISSUE THREAD

**Issue by tim-oe** [kncept/junit-reporter#12]
i have a project where there is a subproject under the folder "app"
junit placing the result files at "app\build\test-results\junit-platform"

i have the following config in the subproject build.gradle:

junitHtmlReport {
    //RAG status css overrides
    cssRed = 'red'
    cssAmber = 'orange'
    cssGreen = 'green'

    //Processing directories
    //testResultsDir = "${buildDir}/test-results"
    testResultsDir = "${buildDir}/test-results/junit-platform"
    testReportsDir = "${buildDir}/reports/tests"

    //Fail build when no XML files to process
    failOnEmpty = true
}

I've tried both testResultsDir  settings and neither one works.
how do I see what actual dir it's looking into, I don't see
any debug logging in the source.

any help will be appreciated.

**Comment by tim-oe** [comment]
I commented out the testResultsDir testReportsDir and it generated the report but where are the details of the failed test?

**Comment by tim-oe** [comment]
ok found it, the arrow on the individual tests. is there any way navigate to failed tests from other views?

**Comment by nkrul** [comment]
Hi  :)
There is only the simple tabbed view... everything on one page.
Feel free to change the filter for 'test status' from a string to a drop down - patch requests accepted.

**Comment by nkrul** [comment]
Closing old issue... underlying is resolved
