### ISSUE TITLE
Combine subprojects

### ISSUE THREAD

**Issue by tobad357** [kncept/junit-reporter#17]
We have a lot of subprojects and I'm wondering if it is possible to combine the reports from all subprojects into one master junit report?

We tried configuring on root project but just get an error 
```
Execution failed for task ':junitHtmlReport'.
> com.kncept.junit.reporter.exception.TestReporterFailure: No XML Reports to process
```

**Comment by nkrul** [comment]
Perhaps try something like this in your root project

maxDepth = 9
testResultsDir = 'test-results'
testReportsDir = '.'

It's not what I'd call elegant, but it should work.

This project isn't really designed for that use case... but if you work out a better solutions, PR's are welcome.
