### ISSUE TITLE
Enhancement: a single summary report for all sourceSets (and engines).

### ISSUE THREAD

**Issue by tenwit** [kncept/junit-reporter#2]
JUnit produces one `build/test-results-<sourceSet>/TEST-junit-<engine>.xml` file per sourceSet. The plugin produces one directory per file, `build/tests/junit-<sourceSet>`. Is there a way to merge the results, or get an overall summary page that shows all the source sets? Maybe just a new `build/tests/index.html` file that includes the other files in iframes?

Possibly engines could be merged like this too; I haven't used more than the jupiter engine, so I don't know how that is currently working.

For your ATDD / spec by example pleasure:
> As a developer
> I want to publish one page (and supporting directories) to my CI server or report dashboard
> So that my team can see easily all results and find where the failures are with minimal effort

**Comment by nkrul** [comment]
Simple merging is possible, and works with how "most people" would run the tool (single server, homogeneous environment). If you want something more complicated than that, send a pull request :)

**Comment by tenwit** [comment]
That's what I think will help. My specific use case is that I have an integrationTest phase that runs after `test` and before `check`, and I'd like to see both sets of results in a single report. Here's gradle code I'm using:
_Before `dependencies`_
```
    configurations {
        integrationTestCompile.extendsFrom testCompile
        integrationTestRuntime.extendsFrom testRuntime
    }

    sourceSets {
        integrationTest {
            java {
                compileClasspath += main.output + test.output
                runtimeClasspath += main.output + test.output
                srcDir file('src/integrationTest/java')
            }
            resources.srcDir file('src/integrationTest/resources')
        }
    }
```

_After `dependencies`_
```
    def integrationTest = task('integrationTest', type: JavaExec, group: 'Verification') {
        description = 'Runs integration tests.'
        dependsOn testClasses
        shouldRunAfter test
        classpath = sourceSets.integrationTest.runtimeClasspath

        main = 'org.junit.platform.console.ConsoleLauncher'
        args = ['--scan-class-path', sourceSets.integrationTest.output.classesDir.absolutePath,
                '--reports-dir', "${buildDir}/test-results/junit-integrationTest"]
    }

    check {
        dependsOn integrationTest
    }
```
(I couldn't find any other way to get integrationTest working with the junit5 plugin; this workaround will do until the Gradle team take over the plugin.)

**Comment by nkrul** [comment]
Yeah, the junit5 plugins could certainly use some some work. At least gradle is easy to plug what you want in.
Try v1.0.0... should do what you are after, but you will need to use a little config block to enable it (aggregation... see Readme for details)
