### ISSUE TITLE
Can't be applied to Android projects

### ISSUE THREAD

**Issue by Rosomack** [kncept/junit-reporter#3]
Hi there, looking at the source code I realise this doesn't work at all for Android tests.

We're currently implementing running JUnit 5 tests using this plugin: https://github.com/mannodermaus/android-junit5

Any plans on supporting Android anytime soon?

**Comment by nkrul** [comment]
Why doesn't it work? What error are you getting?
I don't have any android projects going on at the moment, so you'll have to provide some details. 
I presume that its looking in the wrong directory for android (arguably, android isn't using the conventional output directory). Could you provide details about your project structure?

**Comment by Rosomack** [comment]
Sorry for the delay in answering. I've made a mistake in the setup - the plugin does work but there are a couple of issues I'd like to discuss. Closing this and opening other issues.
