### ISSUE TITLE
Dependency on "check" task

### ISSUE THREAD

**Issue by Rosomack** [kncept/junit-reporter#4]
This is more of a discussion / question than a bug report.

We're trying to run the plugin in our Android tests. The plugin works, but the assumption that the "check" task is always the correct one to depend on is constraining us. I think that this task is not necessarily the correct one to depend on in every project.

For instance, we typically run checkstyle separate from our unit tests. Also to run our unit tests we use a specific buildType of the project, for example `junitPlatformTestUkDebug`. The check on the other hand would run all variants of unit tests and checkstyle before running the `junitHtmlResults` task.

I'm not necessarily saying it's wrong, but it would be great more fine-grained control. For now I've forked the project and removed the dependency on the `check` task so that we can use the plugin manually.

**Comment by nkrul** [comment]
I'd wanted to find it to junitPlatformTest... but I can't see that task inside the plugin whilst defining it.
I've removed the dependsOn, so now it just performs the finalizedBy operation.
Readme also updated.

A release will be waiting on the other issue you raised.
