### ISSUE TITLE
Support for seeing details of failed tests

### ISSUE THREAD

**Issue by sbrannen** [kncept/junit-reporter#8]
First and foremost... very cool that you created this project! 👍 

Do you have any plans to support a detailed page for failed tests?

Or is that feature already there, and I just missed it?

**Comment by nkrul** [comment]
Hi.
The project is pretty simple, currently what you see is what you get.
I got stuck on some System.out processing (its not the same for JUnit4 vs JUnit5).
I'll add some better details, but I need to redo the build first

**Comment by nkrul** [comment]
The test details view has an 'unsuccessful reason' added to it.
Its pretty basic.
Care to poke at https://github.com/kncept/junit-reporter/issues/9 for me?
I'll do a release over the weekend.

**Comment by sbrannen** [comment]
>  The project is pretty simple, currently what you see is what you get.

OK

**Comment by sbrannen** [comment]
> Care to poke at #9 for me?

Well, I'm not a JavaScript guy, so I wouldn't be much help there. 😉 

> I'll do a release over the weekend.

Looking forward to it.

**Comment by nkrul** [comment]
Weekend? I was bored... v1.0.3 should be available on Maven Central now.

**Comment by sbrannen** [comment]
Cool.

I'll check it out...

**Comment by sbrannen** [comment]
> The test details view has an 'unsuccessful reason' added to it.

I tried it out, and the reason does indeed show up. So, that's much better!

But... I'd recommend that you wrap the reason in `<pre></pre>` tags so that newlines are not lost.

**Comment by sbrannen** [comment]
Also, it would be really useful is the stack trace could be made available as well. 😇

**Comment by nkrul** [comment]
I'll fix the newlines. I did have them wrapped in pre tags at one stage... it must have vanished.
I'll add a multiline test failure message. Edge cases...

Adding in the exception (or any more details) would be too messy... I want to, but https://github.com/kncept/junit-reporter/issues/9 has to be done first.
I'm not a .js guy either, so I picked a super simple component. Now it needs to be upgraded.

**Comment by sbrannen** [comment]
> I'll fix the newlines. I did have them wrapped in pre tags at one stage... it must have vanished.

Sounds good.

> I'll add a multiline test failure message. Edge cases...

Well, if you're using `assertAll(...)` with JUnit Jupiter, it turns out not to be that much of an _edge case_. 😉 

> Adding in the exception (or any more details) would be too messy... I want to, but #9 has to be done first. I'm not a .js guy either, so I picked a super simple component. Now it needs to be upgraded.

Understood.

Cheers!
